import type { Metadata } from "next";
import { Bitter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { GlobalNav } from "@/components/global-nav";

const bitter = Bitter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Baseline",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bitter.className} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <GlobalNav />
          <div className="min-h-screen w-full bg-zinc-100 dark:bg-zinc-950">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
